export * as schema from "./schema.js";
export {
  accounts,
  accountIdentities,
  accountMcpTokens,
  events,
  outbox,
  runs,
  taskGrants,
  accountBaselineRules,
  approvals,
  proposedGrants,
  compileReports,
  runDedupe,
  tasks,
  taskEmits,
  taskConsumes,
  eventDefs,
  workflows,
  workflowExecutions,
  workflowVersions,
  schedules,
  taskState,
  workflowShares,
  traceEntries,
  artifacts,
  cdpEndpoints,
  endpointLeases,
  browserProfiles,
  browserSessions,
  browserProfileLeases,
  browserAllocationRequests,
  browserWorkers,
  browserSessionActivity,
  browserRecordingSegments,
  secrets,
  secretGrants,
  secretAccessLog,
  storeSchemas,
  storeWriteGrants,
  compiledScripts,
  compileJobs,
  engineStatus,
} from "./schema.js";
export {
  RUN_STATUSES,
  MISSED_POLICIES,
  OVERLAP_POLICIES,
  TRACE_KINDS,
  TASK_KINDS,
  SECRET_TIERS,
  SECRET_ACCESS_ACTIONS,
  STORE_MIGRATION_CLASSES,
  COMPILED_SCRIPT_STATUSES,
  COMPILE_JOB_STATUSES,
  COMPILE_JOB_REASONS,
  APPROVAL_STATUSES,
  PROPOSED_GRANT_STATUSES,
  BROWSER_SESSION_STATUSES,
  BROWSER_WORKER_STATUSES,
  BROWSER_RECORDING_STATUSES,
  BROWSER_RECORDING_SEGMENT_STATUSES,
  EXECUTION_STATUSES,
} from "./schema.js";
export type {
  RunStatus,
  MissedPolicy,
  OverlapPolicy,
  TraceKind,
  TaskKind,
  TraceEntryRow,
  ArtifactRow,
  EventRow,
  NewEvent,
  OutboxRow,
  RunRow,
  NewRun,
  TaskGrantRow,
  AccountBaselineRuleRow,
  ApprovalRow,
  ApprovalStatus,
  ProposedGrantRow,
  ProposedGrantStatus,
  CompileReportRow,
  TaskRow,
  EventDefRow,
  TaskEmitRow,
  TaskConsumeRow,
  WorkflowRow,
  AccountRow,
  AccountIdentityRow,
  AccountMcpTokenRow,
  WorkflowExecutionRow,
  ExecutionStatus,
  WorkflowVersionRow,
  ScheduleRow,
  WorkflowShareRow,
  CdpEndpointRow,
  EngineStatusRow,
  NewCdpEndpoint,
  EndpointLeaseRow,
  BrowserProfileRow,
  BrowserSessionRow,
  BrowserProfileLeaseRow,
  BrowserAllocationRequestRow,
  BrowserWorkerRow,
  BrowserSessionActivityRow,
  BrowserRecordingSegmentRow,
  BrowserSessionStatus,
  BrowserWorkerStatus,
  BrowserRecordingStatus,
  BrowserRecordingSegmentStatus,
  SecretTier,
  SecretRow,
  NewSecret,
  SecretGrantRow,
  SecretAccessAction,
  SecretAccessLogRow,
  StoreMigrationClass,
  StoreSchemaRow,
  NewStoreSchema,
  StoreWriteGrantRow,
  CompiledScriptRow,
  CompiledScriptStatus,
  CompileJobRow,
  CompileJobStatus,
  CompileJobReason,
} from "./schema.js";
// test-db is deliberately NOT re-exported here: it imports @tabductor/testkit, which
// imports playwright-core, and this barrel is what `apps/web` bundles — the chain broke
// `next build`. Tests import `@tabductor/db/test-db` directly.
export {
  createDb,
  migrateDb,
  migrationsFolder,
  MIGRATION_DRIFT,
  type Db,
  type DbHandle,
} from "./client.js";
