import { afterAll, beforeAll, expect, it } from "vitest";
import { createMigratedTestDb, type MigratedTestDb } from "@tabductor/db/test-db";
import { events, runs } from "@tabductor/db";
import { eq } from "drizzle-orm";
import { dispatchEvent } from "@tabductor/engine";
import { createCaller } from "../../apps/web/src/server/router.js";
let db: MigratedTestDb;
beforeAll(async () => { db = await createMigratedTestDb(); });
afterAll(async () => { await db?.close(); });
it("keeps outputs as evidence without creating subscriptions, decision nodes or downstream runs", async () => {
  const api = createCaller({ db: db.db });
  const workflow = await api.workflow.createFromPrompt({ prompt: "Collect products, prepare the destination and save them in this session" });
  const execution = await api.workflow.trigger({ workflowId: workflow.workflowId });
  const { publish } = await import("@tabductor/bus");
  const event = await publish(db.db, { type: "collection.complete", executionId: execution.executionId, sourceTaskId: workflow.versionId, sourceRunId: execution.runs[0]!.runId!, packet: { products: [{ id: "one" }] } });
  expect(await dispatchEvent(db.db, event)).toEqual([]);
  expect(await dispatchEvent(db.db, event)).toEqual([]);
  expect(await db.db.select().from(runs).where(eq(runs.executionId, execution.executionId))).toHaveLength(1);
  expect((await db.db.select().from(events).where(eq(events.eventId, event.eventId)))[0]?.packet).toEqual({ products: [{ id: "one" }] });
});
