import { afterAll, beforeAll, expect, it } from "vitest";
import { createMigratedTestDb, type MigratedTestDb } from "@tabductor/db/test-db";
import { runs, tasks } from "@tabductor/db";
import { eq } from "drizzle-orm";
import { createCaller } from "../../apps/web/src/server/router.js";
import { createWorkflowControl } from "../../apps/web/src/server/workflow-mcp.js";
let db: MigratedTestDb;
beforeAll(async () => { db = await createMigratedTestDb(); });
afterAll(async () => { await db?.close(); });
it("saves the exact prompt without authoring, rejects stale changes, and starts one runtime", async () => {
  const context = { db: db.db };
  const api = createCaller(context);
  const control = createWorkflowControl(context);
  const prompt = "  Collect the prices.\nSave each product, then report the result.  ";
  const created = await api.workflow.createFromPrompt({ prompt });
  expect((await api.workflow.get({ id: created.workflowId })).definition?.prompt).toBe(prompt);
  const unchanged = await api.workflow.savePrompt({ workflowId: created.workflowId, expectedVersionId: created.versionId, definition: { prompt } });
  expect(unchanged.versionId).toBe(created.versionId);
  await control.update({ workflowId: created.workflowId, prompt: "New request" });
  await expect(api.workflow.savePrompt({ workflowId: created.workflowId, expectedVersionId: created.versionId, definition: { prompt: "Stale" } })).rejects.toThrow();
  const [first, second] = await Promise.all([api.workflow.trigger({ workflowId: created.workflowId, requestId: "same" }), api.workflow.trigger({ workflowId: created.workflowId, requestId: "same" })]);
  expect(first).toEqual(second);
  expect(first.accepted).toBe(1);
  expect(await db.db.select().from(runs).where(eq(runs.executionId, first.executionId))).toHaveLength(1);
  const version = await api.workflow.get({ id: created.workflowId });
  expect(await db.db.select().from(tasks).where(eq(tasks.workflowVersionId, version.versionId!))).toHaveLength(1);
  await control.schedule({ workflowId: created.workflowId, cron: "*/5 * * * *", timezone: "UTC" });
  expect((await api.workflow.get({ id: created.workflowId })).definition?.schedule).toEqual({ cron: "*/5 * * * *", timezone: "UTC", enabled: true });
  expect((await api.workflow.trigger({ workflowId: created.workflowId, requestId: "same" })).executionId).toBe(first.executionId);
});
