import Link from "next/link";
import { createServerCaller } from "../../server/router.js";
import { AdminFeedback, AdminRateForm, WelcomeForm, CouponForm, CouponActions, ExpenseForm, ProxyForm, ProxySync, ReconcileChargeForm } from "../../components/admin-forms.js";
import { formatUsd, usdMicros } from "@tabductor/core";
export const dynamic="force-dynamic";
export const metadata={title:"Administration"};
const tabs=["overview","users","pricing","coupons","providers"];
export default async function AdminPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const query=await searchParams,tab=tabs.includes(query.tab??"")?query.tab!:"overview";
  const until=query.to??new Date().toISOString().slice(0,10),since=query.from??new Date(Date.now()-29*86400000).toISOString().slice(0,10);
  const from=new Date(since+"T00:00:00Z"),to=new Date(new Date(until+"T00:00:00Z").getTime()+86400000);
  const page=Math.max(0,Number(query.page)||0),caller=await createServerCaller();
  const [settings,overview,users]=await Promise.all([caller.admin.settings(),tab==="overview"?caller.admin.overview({from,to,page,...(query.account?{accountId:query.account}:{}),...(query.category?{category:query.category}:{}),...(query.provider?{provider:query.provider}:{}),...(query.funding==="byo"||query.funding==="platform"?{funding:query.funding}:{})}):null,tab==="users"?caller.admin.users({page,query:query.q??""}):null]);
  const pendingCharges=tab==="providers"?await caller.admin.pendingCharges():[];
  const costTotal=overview?.costs.reduce((sum,row)=>sum+usdMicros(row.amountUsd),0)??0;
  const usd=overview?.sales.find(row=>row.currency==="USD");
  const refunds=Number(overview?.refunds.find(row=>row.currency==="USD")?.amount??0);
  const net=(Number(usd?.gross??0)-Number(usd?.fee??0)-Number(usd?.tax??0)-refunds)*10000;
  const incomplete=(overview?.costs.some(row=>row.unknown>0)??false)||Boolean(usd?.missing)||Boolean(overview?.untrackedCosts)||refunds>0||Boolean(query.category||query.provider||query.funding);
  const days=new Map<string,number>();for(const row of overview?.usage??[])days.set(row.day,(days.get(row.day)??0)+usdMicros(row.amountUsd));
  const max=Math.max(1,...days.values());
  return <div className="admin-page"><div className="page-heading"><div><span className="eyebrow">Administration · USD</span><h1>Usage & earnings</h1><p className="muted">Wallet balances, customer charges, and operating costs.</p></div></div>
    <nav className="admin-tabs" aria-label="Administration">{tabs.map(item=><Link key={item} href={`/admin?tab=${item}`} aria-current={item===tab?"page":undefined}>{item==="pricing"?"Pricing & costs":item[0]!.toUpperCase()+item.slice(1)}</Link>)}</nav>
    <AdminFeedback/>
    {tab==="overview"&&overview?<>
      <form className="admin-filters" method="get"><input type="hidden" name="tab" value="overview"/><label>From <input type="date" name="from" defaultValue={since} required/></label><label>Through <input type="date" name="to" defaultValue={until} required/></label><label>Account ID <input name="account" defaultValue={query.account}/></label><label>Usage category <select name="category" defaultValue={query.category??""}><option value="">All</option>{["browser","solver","model","proxy","summary","overhead"].map(c=><option key={c}>{c}</option>)}</select></label><label>Provider <input name="provider" defaultValue={query.provider}/></label><label>Model funding <select name="funding" defaultValue={query.funding??""}><option value="">All</option><option value="byo">BYO</option><option value="platform">Platform</option></select></label><button>Apply</button></form>
      <p className="muted">Dates use UTC. Provider and funding filters apply to provider costs and model usage; payment totals remain scoped to the account and dates.</p>
      <div className="admin-metrics"><div><span>Net USD sales after refunds, tax & fees</span><strong>{usd?.missing||refunds>0?"Incomplete":formatUsd(net)}</strong></div><div><span>Recorded operating costs</span><strong>{formatUsd(costTotal)}</strong></div><div><span>Estimated operating profit</span><strong>{incomplete?"Incomplete":formatUsd(net-costTotal)}</strong></div><div><span>Accounts using BYO models</span><strong>{overview.byo.active} / {overview.byo.total}</strong><small>{overview.byo.configured} have an active credential</small></div></div>
      {incomplete?<p className="banner" role="status">Profit needs complete, unfiltered cost data. Missing historical costs, fees, or refund fee/tax adjustments are flagged rather than treated as zero.</p>:null}
      <h2>USD spent by day</h2>{days.size?<div className="admin-chart" role="img" aria-label="Daily customer USD spending; exact values follow in the usage table">{[...days].map(([day,value])=><div key={day} title={`${day}: ${formatUsd(value)}`}><span style={{height:`${Math.max(2,value/max*100)}%`}}/><small>{day.slice(5)}</small></div>)}</div>:<p className="muted">No settled usage in this period.</p>}
      <div className="table-scroll"><table className="ledger"><caption>Settled customer usage</caption><thead><tr><th>Date</th><th>Category</th><th>Operations</th><th>USD spent</th></tr></thead><tbody>{overview.usage.map(row=><tr key={`${row.day}:${row.category}`}><td>{row.day}</td><td>{row.category}</td><td>{row.operations}</td><td>${row.amountUsd}</td></tr>)}</tbody></table></div>
      <h2>Operating costs</h2><div className="table-scroll"><table className="ledger"><thead><tr><th>Category</th><th>USD cost</th><th>Unpriced operations</th></tr></thead><tbody>{overview.costs.map(row=><tr key={row.category}><td>{row.category}</td><td>${row.amountUsd}</td><td>{row.unknown}</td></tr>)}</tbody></table></div>
      <h2>Metered usage</h2><div className="table-scroll"><table className="ledger"><thead><tr><th>Category / provider</th><th>Task or unit</th><th>Quantity</th></tr></thead><tbody>{overview.quantities.map(row=><tr key={`${row.category}:${row.provider}:${row.item}`}><td>{row.category} / {row.provider}</td><td>{row.item}</td><td>{row.quantity}{row.category==="proxy"?" bytes":row.category==="browser"?" started minutes":" solves"}</td></tr>)}</tbody></table></div>
      <h2>Sales by currency</h2><p className="muted">Other currencies are kept separate from the USD profit estimate. Wallet additions are prepaid balances, separate from payment revenue.</p><div className="table-scroll"><table className="ledger"><thead><tr><th>Currency</th><th>Payments</th><th>Refunds</th><th>Fees</th></tr></thead><tbody>{overview.sales.map(row=><tr key={row.currency}><td>{row.currency}</td><td>{row.currency==="USD"?formatUsd(Number(row.gross)*10000):`${row.gross} minor units`}</td><td>{row.currency==="USD"?formatUsd(Number(row.refunds)*10000):`${row.refunds} minor units`}</td><td>{row.currency==="USD"?formatUsd(Number(row.fee)*10000):`${row.fee} minor units`}</td></tr>)}</tbody></table></div>
      <h2>Models</h2><div className="table-scroll"><table className="ledger"><thead><tr><th>Provider / model</th><th>Funding</th><th>Calls</th><th>Input / output tokens</th></tr></thead><tbody>{overview.models.map(row=><tr key={`${row.provider}:${row.model}:${row.funding}`}><td>{row.provider} / {row.model}</td><td>{row.funding}</td><td>{row.calls}</td><td>{row.input} / {row.output}</td></tr>)}</tbody></table></div>
      <h2>Recent wallet reservations</h2><div className="table-scroll"><table className="ledger"><thead><tr><th>Account</th><th>Category</th><th>State</th><th>Reserved</th><th>Spent</th></tr></thead><tbody>{overview.recent.map(row=><tr key={row.id}><td><Link href={`/admin?account=${encodeURIComponent(row.accountId)}`}>{row.accountId}</Link></td><td>{row.category}</td><td>{row.status}</td><td>${row.reservedUsd}</td><td>{row.spentUsd===null?"Pending":`$${row.spentUsd}`}</td></tr>)}</tbody></table></div>
      <nav className="row" aria-label="Usage pages">{page>0?<Link href={`/admin?${new URLSearchParams({...Object.fromEntries(Object.entries(query).filter((entry):entry is [string,string]=>typeof entry[1]==="string")),page:String(page-1)})}`}>← Previous</Link>:null}{overview.hasMore?<Link href={`/admin?${new URLSearchParams({...Object.fromEntries(Object.entries(query).filter((entry):entry is [string,string]=>typeof entry[1]==="string")),page:String(page+1)})}`}>Next →</Link>:null}</nav>
      <h2>Balance coupon redemptions</h2><ul>{overview.redemptions.map(row=><li key={row.code}>{row.code}: {row.redemptions}</li>)}</ul>
    </>:null}
    {tab==="users"&&users?<><form className="row"><input type="hidden" name="tab" value="users"/><label>Find account <input name="q" defaultValue={query.q}/></label><button>Search</button></form><p className="muted">Legacy wallets convert to USD automatically after outstanding usage settles.</p><div className="table-scroll"><table className="ledger"><thead><tr><th>Account</th><th>Available USD</th><th>Reserved USD</th><th>Spent USD</th><th>BYO key</th><th>Actions</th></tr></thead><tbody>{users.items.map(row=><tr key={row.id}><td>{row.name}<br/><Link href={`/admin?account=${encodeURIComponent(row.id)}`}>{row.id}</Link></td><td>{row.availableUsd===null?"Legacy balance":`$${row.availableUsd}`}</td><td>{row.reservedUsd===null?"—":`$${row.reservedUsd}`}</td><td>{row.spentUsd===null?"—":`$${row.spentUsd}`}</td><td>{row.byo?"Connected":"No"}</td><td>{row.moneyUnit!=="usd_micro"?"Automatic conversion pending":null}</td></tr>)}</tbody></table></div><nav className="row" aria-label="Account pages">{page>0?<Link href={`/admin?tab=users&page=${page-1}&q=${encodeURIComponent(query.q??"")}`}>← Previous</Link>:null}{users.hasMore?<Link href={`/admin?tab=users&page=${page+1}&q=${encodeURIComponent(query.q??"")}`}>Next →</Link>:null}</nav></>:null}
    {tab==="pricing"?<><div className="table-scroll"><table className="ledger"><caption>Current rate versions</caption><thead><tr><th>Usage</th><th>Provider</th><th>Task / unit</th><th>Customer USD price</th><th>Provider USD cost</th></tr></thead><tbody>{settings.rates.map(rate=><tr key={rate.id}><td>{rate.category}</td><td>{rate.provider||"Browser"}</td><td>{rate.item}</td><td>${rate.chargeUsd}</td><td>{rate.costUsd===null?"Unknown":`$${rate.costUsd}`}</td></tr>)}</tbody></table></div><div className="admin-form-grid"><AdminRateForm/><WelcomeForm amount={settings.welcomeUsd}/><ExpenseForm/></div></>:null}
    {tab==="coupons"?<><CouponForm/><div className="table-scroll"><table className="ledger"><thead><tr><th>Code</th><th>Benefit</th><th>Limit / expires</th><th>Status</th><th>Actions</th></tr></thead><tbody>{settings.coupons.map(coupon=><tr key={coupon.code}><td>{coupon.code}</td><td>{coupon.kind==="percent"?`${coupon.amount}%`:`$${coupon.amount}`} · {coupon.kind}</td><td>{coupon.maxRedemptions??"Unlimited"} / {coupon.expiresAt?.toISOString().slice(0,10)??"Never"}</td><td>{coupon.syncError??(coupon.disabled?"Disabled":"Active")}</td><td><CouponActions coupon={coupon}/></td></tr>)}</tbody></table></div></>:null}
    {tab==="providers"?<><h2>IPRoyal Residential</h2><p>{settings.proxyConfigured?"API token configured":"Set IPROYAL_API_TOKEN to enable usage imports."}</p><p>Last successful import: {String(settings.sync.lastSuccess??"Never")}</p>{settings.sync.error?<p role="alert">{String(settings.sync.error)}</p>:null}<ProxySync configured={settings.proxyConfigured}/><ProxyForm/><ul>{settings.proxies.map(proxy=><li key={proxy.hash}>{proxy.label} · {proxy.accountId??"Shared overhead"}</li>)}</ul><h2>Action descriptions</h2><p>{settings.summaryConfigured?"Platform OpenAI key configured":"Set OPENAI_API_KEY to enable action descriptions."} Model: {process.env.ACTION_SUMMARY_MODEL||"gpt-5.4-nano"}. These calls are platform overhead.</p><h2>Outstanding charges</h2><ul>{pendingCharges.map(charge=><li key={charge.id}>{charge.id} · {charge.account_id} · {charge.category} · {charge.reservedUsd===null?`${charge.legacyUnits} legacy credits`:`$${charge.reservedUsd}`} reserved</li>)}</ul><ReconcileChargeForm/><h2>Workflow deletion jobs</h2><ul>{settings.deletions.map(job=><li key={job.workflowId}>{job.workflowId}: {job.status}{job.error?` · ${job.error}`:""}</li>)}</ul></>:null}
    <details className="admin-audit"><summary>Recent administrative changes</summary><ul>{settings.audits.map(a=><li key={a.id}>{a.createdAt.toISOString()} · {a.actorId} · {a.action}</li>)}</ul></details>
  </div>;
}
